@istest(seeAlldata=true)
public class updatecontactrolecounttest{
static testmethod void method1(){
//OpportunityContactRole opr = [SELECT ContactId,Id,OpportunityId,Role FROM OpportunityContactRole limit 1];
Account acc=new Account();
/*
acc.name='Test';
acc.CurrencyIsoCode='BRL';
insert acc;
Opportunity opp=new Opportunity();
opp.name='Test';
opp.Type='New Business';
opp.StageName='Prospect';
opp.CloseDate=system.now().date();
//opp.ForecastCategory='Omitted';
opp.CurrencyIsoCode='AUD';
opp.Accountid=acc.id;
insert opp;
*/
} 
}